---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.Values.mas_instance_id }}"
  namespace: openshift-gitops
spec:
  destination:
    server: '{{.Values.destination}}'
  ignoreDifferences:
    - group: cert-manager.io
      jsonPointers:
        - /spec/
        - /metadata/
        - /status/
      kind: Certificate
    - group: v1
      jsonPointers:
        - /spec/
        - /metadata/
        - /status/
      kind: Secret
  project: "{{.Values.cluster_name}}-{{.Values.mas_instance_id }}"
  source:
    helm:
      parameters:
        - name: config.presync.mongo
          value: 'false'
        - name: config.presync.sls
          value: 'false'
        - name: config.presync.uds
          value: 'false'
        - name: domain
          value: >-
            {{.Values.domain}}
        - name: mas_instance_id
          value: "{{.Values.mas_instance_id }}"
        - name: mas_channel
          value: "{{.Values.config.core.version}}"
        - name: config.postsync.suite_config
          value: 'false'
    path: config/argocd-mas/mas-core
    repoURL: 'https://github.com/CAIOFCP/masoncloud-argocd.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
