---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-mas-manage-operator-group
  namespace: "mas-{{.Values.mas_instance_id}}-manage"
  annotations:
    argocd.argoproj.io/sync-wave: "02"
spec:
  targetNamespaces:
    - "mas-{{.Values.mas_instance_id}}-manage"
